apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atlantis.fullname" . }}
  labels: {{- include "atlantis.labels" . | nindent 4 }}
data:
  repos.yaml: |
    {{- .Values.repoConfig | nindent 4 }}
