{{- if not .Values.cluster.tokenSecretName }}
{{- $name := include "atlantis.tokenSecretName" . }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels: {{- include "atlantis.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- if and $existing $existing.data $existing.data.token }}
  token: {{ $existing.data.token }}
  {{- else }}
  token: {{ randAlphaNum 48 | b64enc }}
  {{- end }}
{{- end }}
