apiVersion: v1
kind: Service
metadata:
  name: {{ include "atlantis.fullname" . }}
  labels: {{- include "atlantis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "atlantis.selectorLabels" . | nindent 4 }}
  ports:
    # Only the public port. The cluster port is reached pod-to-pod.
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
