//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanRisk) DeepCopyInto(out *PlanRisk) {
	*out = *in
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]PlanRiskFinding, len(*in))
		copy(*out, *in)
	}
	in.AssessedAt.DeepCopyInto(&out.AssessedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanRisk.
func (in *PlanRisk) DeepCopy() *PlanRisk {
	if in == nil {
		return nil
	}
	out := new(PlanRisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlanRiskFinding) DeepCopyInto(out *PlanRiskFinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlanRiskFinding.
func (in *PlanRiskFinding) DeepCopy() *PlanRiskFinding {
	if in == nil {
		return nil
	}
	out := new(PlanRiskFinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySetApproval) DeepCopyInto(out *PolicySetApproval) {
	*out = *in
	if in.Hashes != nil {
		in, out := &in.Hashes, &out.Hashes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySetApproval.
func (in *PolicySetApproval) DeepCopy() *PolicySetApproval {
	if in == nil {
		return nil
	}
	out := new(PolicySetApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySetStatus) DeepCopyInto(out *PolicySetStatus) {
	*out = *in
	if in.Approvals != nil {
		in, out := &in.Approvals, &out.Approvals
		*out = make([]PolicySetApproval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hashes != nil {
		in, out := &in.Hashes, &out.Hashes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySetStatus.
func (in *PolicySetStatus) DeepCopy() *PolicySetStatus {
	if in == nil {
		return nil
	}
	out := new(PolicySetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	if in.PolicyStatus != nil {
		in, out := &in.PolicyStatus, &out.PolicyStatus
		*out = make([]PolicySetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PlanRisk != nil {
		in, out := &in.PlanRisk, &out.PlanRisk
		*out = new(PlanRisk)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequest) DeepCopyInto(out *PullRequest) {
	*out = *in
	out.BaseRepo = in.BaseRepo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequest.
func (in *PullRequest) DeepCopy() *PullRequest {
	if in == nil {
		return nil
	}
	out := new(PullRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullStatus) DeepCopyInto(out *PullStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullStatus.
func (in *PullStatus) DeepCopy() *PullStatus {
	if in == nil {
		return nil
	}
	out := new(PullStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PullStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullStatusList) DeepCopyInto(out *PullStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PullStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullStatusList.
func (in *PullStatusList) DeepCopy() *PullStatusList {
	if in == nil {
		return nil
	}
	out := new(PullStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PullStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullStatusSpec) DeepCopyInto(out *PullStatusSpec) {
	*out = *in
	out.Pull = in.Pull
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = make([]ProjectStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullStatusSpec.
func (in *PullStatusSpec) DeepCopy() *PullStatusSpec {
	if in == nil {
		return nil
	}
	out := new(PullStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repo) DeepCopyInto(out *Repo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repo.
func (in *Repo) DeepCopy() *Repo {
	if in == nil {
		return nil
	}
	out := new(Repo)
	in.DeepCopyInto(out)
	return out
}
